/****************************************************************************************************************************************
	File:		T_FATO_PEDIDOS.INC 
		
	Author:		Felipe Garvin
	Email:		felipe.garvin@bix-tech.com
	
	Version:	1.0
	Date:		19/07/2024
	
	Objetivo: Otimizações importantes são feitas nesse script.
	
****************************************************************************************************************************************/

AUTONUMBER KEY_CLIENTE USING A; // realizado o AUTONUMBER no campo KEY_CLIENTE pelo motivo do campo ser chave e estar no formato de STRING

